version: git-{branch}-{build}
image:
  - Visual Studio 2017
  - macos

configuration:
- fast

platform:
- x64

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    before_build:
      - cmd: >-
          set BUILD_PATH=shell\linux
          
          set EXTRA_PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
          
          set PATH=%EXTRA_PATH%;%PATH%
          
          if not exist %BUILD_PATH% (mkdir %BUILD_PATH%)
         
          cd %BUILD_PATH%
          
    build_script:
      - cmd: >-
          if "%CONFIGURATION%"=="fast" (mingw32-make -j2 platform=win32)

    after_build:
      - cmd: >-      
          if "%CONFIGURATION%"=="fast" (cd ..\.. && set EXE_PATH=shell\linux\nosym-reicast.exe)
          
          mkdir artifacts
          
          move %EXE_PATH% artifacts\flycast-win_%PLATFORM%-%CONFIGURATION%-%APPVEYOR_REPO_COMMIT%.exe

    artifacts:
      - path: artifacts
        name: flycast-win_$(PLATFORM)-$(CONFIGURATION)-$(APPVEYOR_REPO_COMMIT)

    deploy:
      release: flycast-gdxsv-v$(appveyor_build_version)
      description: 'DC emulator flycast for gdxsv'
      provider: GitHub
      auth_token:
        secure: ENCRYPTED_GITHUB_ACCESS_TOKEN
      artifact: artifacts\flycast-win_%PLATFORM%-%CONFIGURATION%-%APPVEYOR_REPO_COMMIT%.exe
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

  -
    matrix:
      only:
        - image: macos
    
    build_script:
      - cmd: >-
          cd shell\apple
          xcodebuild archive -workspace reicast.xcworkspace -scheme reicast-osx -archivePath flycast.xcarchive

    after_build:
      - cmd: >-
          mv flycast.xcarchive/Products/Applications/Flycast.app Flycast-$APPVEYOR_REPO_COMMIT.app
          7z a Flycast-$APPVEYOR_REPO_COMMIT.zip Flycast-$APPVEYOR_REPO_COMMIT.app

    artifacts:
      - path: Flycast-$APPVEYOR_REPO_COMMIT.zip
