version: git-{branch}-{build}
image:
  - Visual Studio 2017
  - macos

configuration:
- fast

platform:
- x64

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    before_build:
      - cmd: >-
          set BUILD_PATH=shell\linux
          
          set EXTRA_PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
          
          set PATH=%EXTRA_PATH%;%PATH%

          git describe --tags

          if defined %APPVEYOR_REPO_TAG_NAME% set SUFFIX=%APPVEYOR_REPO_TAG_NAME%-%GIT_SHORT_HASH% else for /f "delims=" %%i in ('git describe --tags') do set SUFFIX=%%i
          
          if not exist %BUILD_PATH% (mkdir %BUILD_PATH%)
         
          cd %BUILD_PATH%
          
    build_script:
      - cmd: >-
          if "%CONFIGURATION%"=="fast" (mingw32-make -j2 platform=win32)

    after_build:
      - cmd: >-      
          if "%CONFIGURATION%"=="fast" (cd ..\.. && set EXE_PATH=shell\linux\nosym-reicast.exe)
          
          mkdir artifacts
          
          move %EXE_PATH% artifacts\Flycast-win_%PLATFORM%-%SUFFIX%.exe

    artifacts:
      - path: artifacts
        name: Flycast-win_$(PLATFORM)-$(SUFFIX)

    deploy:
      release: $(APPVEYOR_REPO_TAG_NAME)
      description: 'DC emulator flycast for gdxsv'
      provider: GitHub
      auth_token:
        secure: FbT5TJnObEem2pmSSG85DLyLbsA/BwwDti//D4QVZ1H8zAFPSm5tKlXlIGMOHuVR
      artifact: Flycast-win_$(PLATFORM)-$(SUFFIX)
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

  -
    matrix:
      only:
        - image: macos      
    
    before_build:
      - sh: >-
          export GIT_SHORT_HASH=${APPVEYOR_REPO_COMMIT:0:7}

          cd shell/apple

          mkdir artifacts

    build_script:
      - sh: >-
          xcodebuild archive -workspace reicast.xcworkspace -scheme reicast-osx -archivePath flycast.xcarchive

    after_build:
      - sh: >-
          mv flycast.xcarchive/Products/Applications/Flycast.app Flycast-$APPVEYOR_REPO_TAG_NAME-$GIT_SHORT_HASH.app

          7z a artifacts/Flycast-macOS-$APPVEYOR_REPO_TAG_NAME-$GIT_SHORT_HASH.zip Flycast-$APPVEYOR_REPO_TAG_NAME-$GIT_SHORT_HASH.app "How to Open.pdf"

    artifacts:
      - path: shell/apple/artifacts/Flycast-macOS-$APPVEYOR_REPO_TAG_NAME-$GIT_SHORT_HASH.zip

    deploy:
      release: $(APPVEYOR_REPO_TAG_NAME)
      description: 'DC emulator flycast for gdxsv'
      provider: GitHub
      auth_token:
        secure: FbT5TJnObEem2pmSSG85DLyLbsA/BwwDti//D4QVZ1H8zAFPSm5tKlXlIGMOHuVR
      artifact: shell/apple/artifacts/Flycast-macOS-$APPVEYOR_REPO_TAG_NAME-$GIT_SHORT_HASH.zip
      draft: false
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true

